from __future__ import annotations

import numpy as np

from sklearn.tree import DecisionTreeClassifier

from backend.training.config import RANDOM_STATE
from backend.training.models.base import (
    BaseClassifier,
)


class DecisionTreeModel(
    BaseClassifier
):
    """
    Binary Decision Tree classifier for gesture recognition.

    The model receives fixed-size feature vectors generated by
    the temporal representation stage.

    Labels:

        0 -> negative
        1 -> positive
    """

    def __init__(
        self,
        *,
        max_depth: int | None = None,
        min_samples_split: int = 2,
        min_samples_leaf: int = 1,
        class_weight: str | dict | None = None,
        random_state: int = RANDOM_STATE,
    ) -> None:

        self.model = DecisionTreeClassifier(
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            class_weight=class_weight,
            random_state=random_state,
        )

    @property
    def name(self) -> str:
        return "decision_tree"

    def fit(
        self,
        X: np.ndarray,
        y: np.ndarray,
    ) -> None:

        self._validate_training_data(
            X,
            y,
        )

        self.model.fit(
            X,
            y,
        )

    def predict(
        self,
        X: np.ndarray,
    ) -> np.ndarray:

        self._validate_input_matrix(
            X
        )

        return self.model.predict(
            X
        )

    def predict_proba(
        self,
        X: np.ndarray,
    ) -> np.ndarray:

        self._validate_input_matrix(
            X
        )

        return self.model.predict_proba(
            X
        )

    @property
    def feature_importances(
        self,
    ) -> np.ndarray:
        """
        Return feature importance values learned by the tree.
        """

        self._require_fitted()

        return self.model.feature_importances_

    @property
    def tree_depth(
        self,
    ) -> int:
        """
        Maximum depth of the trained tree.
        """

        self._require_fitted()

        return int(
            self.model.get_depth()
        )

    @property
    def leaf_count(
        self,
    ) -> int:
        """
        Number of leaf nodes in the trained tree.
        """

        self._require_fitted()

        return int(
            self.model.get_n_leaves()
        )

    def _validate_training_data(
        self,
        X: np.ndarray,
        y: np.ndarray,
    ) -> None:

        self._validate_input_matrix(
            X
        )

        if y.ndim != 1:
            raise ValueError(
                "y must be one-dimensional. "
                f"Received shape: {y.shape}"
            )

        if X.shape[0] != y.shape[0]:
            raise ValueError(
                "X and y must contain the same "
                "number of samples."
            )

        if X.shape[0] == 0:
            raise ValueError(
                "Cannot train with zero samples."
            )

        unique_labels = set(
            np.unique(
                y
            ).tolist()
        )

        if not unique_labels.issubset(
            {0, 1}
        ):
            raise ValueError(
                "DecisionTreeModel currently supports "
                "binary labels 0 and 1 only."
            )

        if len(unique_labels) < 2:
            raise ValueError(
                "Training requires both positive "
                "and negative samples."
            )

    def _validate_input_matrix(
        self,
        X: np.ndarray,
    ) -> None:

        if X.ndim != 2:
            raise ValueError(
                "X must have shape "
                "(n_samples, n_features). "
                f"Received: {X.shape}"
            )

        if X.shape[1] == 0:
            raise ValueError(
                "X contains zero features."
            )

        if not np.all(
            np.isfinite(
                X
            )
        ):
            raise ValueError(
                "X contains NaN or infinite values."
            )

    def _require_fitted(
        self,
    ) -> None:

        if not hasattr(
            self.model,
            "tree_",
        ):
            raise RuntimeError(
                "Decision Tree has not been trained yet."
            )